### ISSUE TITLE
Improve push event subscription

### ISSUE THREAD

**Issue by georgievJon** [clouway/clouwaypush#6]
At current moment we use memcache to store relation between subscriber and subscribed push event. When one subscriber is subscribed for many events it send many requests to keep subscription alive. In this case modified data is increased and update of memcache is slow down. Average time of one "keep alive" request is 1second.

Suggest: We can use search API (cuse) to persist subscriptions. In this case subscribers for given event will be loaded with query. Outdated subscriptions will not be loaded and will be removed from some cron job.

log of request
![keep alive log](https://cloud.githubusercontent.com/assets/300624/7347232/1fc15b1a-ecef-11e4-8219-084d990716e8.png)

**Comment by mgenov** [comment]
Subscriber should send keep alive for the session, not for particular subscription.

**Comment by georgievJon** [comment]
I have not expressed clearly enough.

Every subscriber have list with subscriptions. We send "keep alive" request per subscriber, but in memcache are updated all subscriptions.

May be this diagram can help to understand each other
https://github.com/clouway/clouwaypush/wiki/Subscribe-for-event

**Comment by mgenov** [comment]
What is the average list of subscriptions per user ?

**Comment by mgenov** [comment]
I think that one average user, with access to 4,5 pages should have 4,5 subscriptions which should not be a problem for update.

**Comment by georgievJon** [comment]
One user for CPE have 10-15 subscriptions. We think to reduce this number from UI with unsubscribe.

**Comment by mgenov** [comment]
Can you give me some example list.

**Comment by georgievJon** [comment]
![logs_wan](https://cloud.githubusercontent.com/assets/300624/7349297/a3b9973c-ed00-11e4-9cbf-283809bbab67.png)

**Comment by mgenov** [comment]
I though that valid subscriptions in the push API are: "loadedWanInterfaces", "receivePingResponses", "receiveInstallations". What those identifiers means ? 

Is this an identifier of all send operations ?

**Comment by georgievJon** [comment]
Subscriber: DqPWWhlLSGDLXDt - random generated id for every new tab in browser.

In memcache are stored two relations. First is with key:subscriber with value:map of events. Seconds is key: loadedWanInterfaces with value:map of subscribers.

When is call keepAlive(subscriber) then are updated all related subscriptions.
When is called pushEvent(pushEvent) then are send messages to all subscribers

**Comment by mgenov** [comment]
This night I'll take close look over the code and how things are happening and we can discuss this tomorrow.

**Comment by mgenov** [comment]
Here are some notes that could be discussed tomorrow: 

 * keepAlive service sends list of subscriptions which to be updated for the user. 
  ```java
  void keepAlive(String clientId, ArrayList<String> subscriptions, AsyncCallback<Void> async);
  ```

  Pros: Second map will be removed, and we will update per user this stuff. We could move on the client logic that may schedule different subscriptions by there last used time. When client detects that subscriptions will expire soon, then it should send keepAlive request to ensure that expiration time will be extended.  
  Cons: most used push notifications will suffer for this update, cause more users will be subscribed for a single list of operations. 

  More information can be taken from: 
  https://youtu.be/wWhd9ZwvCyw?list=PLjRJFNWV27jtLp9ZcfsZn0P5jaVHMwD8_&t=2097

 * ActiveSubscriptionsFilterImpl should update in bulk, instead of operation per operation
  ```java
    List<Subscription> subscriptions = subscriptionsRepository.findSubscriptions(type);

    for (Subscription subscription : subscriptions) {
      if(subscription.isActive(currentDate.get())){
        activeSubscriptions.add(subscription);
      }else {
        subscriptionsRepository.removeSubscription(subscription);
      }
    }
  ```
  so memcached key is updated on each expired subscription, where we could update it only once by providing list of expired subscriptions or just the filtered list to be stored for that key. 

 * When user issues command that only he is waiting for responses from it, we could create a subscription (objectId) which to be used for all messages. "userEvetPush1","userEvetPush2", "userEvetPush3" and etc.

Keep in mind that memcache calls could pass for 1ms which should be faster then each search api calls.

**Comment by mlesikov** [comment]
* keepAlive service sends list of subscriptions which to be updated for the user. 
 - currently we  keep that information on the server side in the memcache, it can be changed easily. 
now we just send the subscriberId(the tab unique id, which has open push chanel)

* ActiveSubscriptionsFilterImpl should update in bulk, instead of operation per operation
```java
 List<Subscription> subscriptions = subscriptionsRepository.findSubscriptions(type);
```
I cannot see how this could be implemented with memcache. There are no queries in the memcache, only key - value. 


if we save every new subscription independent and then we can query by subscription type and status(active by the current time) over all subscriptions - that will solve our problems. At this time we have a hard update over each subscription type(which we use ofr key in the memcache) for each subscription.
